[package]
name = "flo-grpc"
version = "0.2.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
prost = "0.9"
prost-types = "0.9"
bytes = "1.2.1"
tonic = "0.6"
anyhow = "1.0"
workspace = { version = "0.18", path = "../../crates/workspace" }

[build-dependencies]
tonic-build = "0.6"
